apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-gen-api          # Name of the Deployment
spec:
  replicas: 3                  # Number of replicas (pods) to create
  selector:
    matchLabels:
      app: text-gen-api      # Select pods with the label 'app: text-gen-api' 
  template:
    metadata:
      labels:
        app: text-gen-api     # Apply label 'app: text-gen-api' to pods
    spec:
      containers:
      - name: text-gen-api  # Container name
        image: text-gen-api # Docker image to user for the container
        envfrom:        
          - configMapRef:           
            name: text-gen-config
        ports:
        - containerPort: 8000 # Port to expose within the container
      